### ISSUE TITLE
[BUG] Volume control doesn't autostart with windows

### ISSUE THREAD

**Issue by Jeremy2131** [radj307/volume-control#108]
Hello, idk where to ask 
I did enabled volume control startup option in the program settings itself and in task manager I see VC process as set to startup but it doesn't, I tried ticking "start with admin privileges" in .exe properties but it doesn't help

Win11 22h2
OS build 22621.2506 if needed
Nothing modified, Volume control installed on C and I'm administrator of my PC

**Comment by radj307** [comment]
It's possible that it is running at startup but is crashing, similar to #85. Since both the application and task manager can see it, it's safe to assume that the registry value does exist.

I will need a log file from when it fails to launch to diagnose anything useful here.

1. Enable all of the log filters:  
![image](https://github.com/radj307/volume-control/assets/1927798/db1629c2-d865-4736-896f-e8a9364c6ace)
2. Restart your computer & do not start volume control manually
3. Find the log file & copy its contents here.  
   *(`%localappdata%/radj307/VolumeControl/VolumeControl.log` for the installer version, same directory as the executable for the portable version)*
   
Make sure you enclose the log file contents in a code block (triple-backticks/grave) when you post it on github, like this:

\`\`\`
\<-- Log goes here
\`\`\`

**Comment by Jeremy2131** [comment]
```
HH:mm:ss:fff              === Log Filter Changed @ Monday, October 30, 2023 5:09:28 PM ===  { LogFilter: 95 (DEBUG, INFO, WARN, ERROR, FATAL, TRACE) }19:09:28:655  [TRACE]     Config property 'LogFilter' was modified.
19:09:28:655  [TRACE]     Saved Config
19:09:53:864  [INFO]      App exited with code 0
19:09:53:865  [TRACE]     Saved Config

```

That's funny but that is it.

**Comment by radj307** [comment]
Strange. I'll do some testing and report back.

**Comment by radj307** [comment]
Cannot replicate on Windows 11 Pro 22H2 Build 22621.1702 VM

**Comment by Jeremy2131** [comment]
Well then you can remove it as a but I guess, something is wrong with my Windows but I will never understand what :(

**Comment by radj307** [comment]
Some questions for you:  
- What version of volume control are you using?
- Are you using the installer or the portable version?
- Where exactly is volume control installed?
- Does volume control start normally when you launch it manually?

**Comment by Jeremy2131** [comment]
You can close the bug, I disabled admin privileges for .exe and it started working.

**Comment by Jeremy2131** [comment]
Im using the latest version, updated to 6.5.1 just now
Using installer version
On C drive in program files with log files in app data as you mentioned above 
Yes it starts manually perfectly 
Anyway VolumeControl now started working normaly with start of Windows so you can close the bug

**Comment by radj307** [comment]
Glad you got it working!  

Problem is resolved, issue closed.
