### ISSUE TITLE
[BUG] 6.5.1 installer - copyright message with wrong © character

### ISSUE THREAD

**Issue by bovirus** [radj307/volume-control#115]
### Version Number

6.5.1

### File

Installer  (VolumeControl-Installer.exe)

### Windows Version

Windows 10 22H2 64bit Italian

### Actual Behaviour

In installer exe file properties in Copyright string there is a wrong charcater (already reported in rpevious version).

![image](https://github.com/radj307/volume-control/assets/1262554/72e1ffee-1283-462f-a931-df0e17408fda)

to avoid this issue instead "©" use "(c)"

### Expected Behaviour

Remove not necessary character

### Reproduction Steps

Right click on installer exe file -> Properties

**Comment by radj307** [comment]
This is caused by an encoding issue on the github actions runner, not an issue with the character itself. No need for a workaround, this can be fixed.

Unicode has multiple different encodings. UTF-8 is the standard that [*should be used everywhere by default*](https://utf8everywhere.org/). For reasons that only Microsoft would know, they decided to use UTF-16 in Windows.

`©` (U+00A9) is encoded as `0x00A9` in UTF-16 and `0xC2` `0xA9` in UTF-8. If you try to load it with UTF-16 it becomes `0x00C2` `0x00A9`, which is `Â©`.

I suspect this is due to `vcsetup.iss` not being saved in UTF-8 with BOM (byte order marks).

**Comment by radj307** [comment]
Saved `vcsetup.iss` in UTF-8 with BOM in b231d08985bea935ba2f84c23df070af6754699b. Will test.

**Comment by radj307** [comment]
[Success!](https://github.com/radj307/volume-control/actions/runs/6758091924)  
![image](https://github.com/radj307/volume-control/assets/1927798/578cde77-ad3c-4445-ac5c-4d440d0b4530)

**Comment by bovirus** [comment]
@radj307 

Thanks.
Please close the ticket.
