### ISSUE TITLE
Duplicate sessions with same name can't all be controlled by same active hotkey, is this intended?

### ISSUE THREAD

**Issue by infcted** [radj307/volume-control#153]
For programs such as Discord. It will have child processes with the same name but different PIDs. Volume Control seems to pick up on these multiples.
![image](https://github.com/radj307/volume-control/assets/62723052/f193ab05-1512-4c52-a760-0609482cbff3)
When using a hotkey to only change volume of a targeted session by that name (and when choosing all in the Target Overrides(s) selection), it will only manipulate one of the multiple sessions.
![image](https://github.com/radj307/volume-control/assets/62723052/5c9b4a32-fe49-421a-8021-44a70175602a)

Should we [FEATURE] a sync of all the sessions with a same name (maybe #54?) or is this a [BUG]?

**Comment by radj307** [comment]
This is *somewhat* intended.  

Discord does use 3 distinct audio sessions: notifications out, VoIP out, & VoIP in.  
But the hotkey target overrides should affect all sessions with the name instead of just the first one, so that is a bug.

I can't promise when I'll be able to fix this as I'm fairly busy atm, but I'll try to do it soon.
