### ISSUE TITLE
D/X-input support

### ISSUE THREAD

**Issue by Switch123456789** [radj307/volume-control#42]
Hey, I wonder if you would consider adding support for Xinput and/or Dinput devices to be used to control the volume?
At the moment I am using AntiMicroX to control some media related stuff with my racing wheel (to mimic radio-controls in ETS2), but I am missing a way to control the volume of the music ONLY. Right now I using a combination of volume-control and AntiMicroX to make it work, but I am sure you can see why this is a pretty janky solution in many regards.

**Comment by radj307** [comment]
Sure, I'll take a look at implementing that for 5.2.4; I expect to have made some progress by later today!

**Comment by Switch123456789** [comment]
Thank you so much!

**Comment by radj307** [comment]
Ok, I've done some research and I have mixed news.

The good news is that it *is* possible to implement this; the bad news is that the implementation will just be replicating what AntiMicroX already does - mapping gamepad input to keys that are recognized by Windows as formal 'Keys' on a keyboard.

I don't think it would make sense for Volume Control to implement its own API for this - AntiMicroX already handles this in the best possible way code-wise despite its jankiness as an actual solution; any implementation I could come up with can't really do better than it anyway.

**Comment by radj307** [comment]
The **Update Joysticks** button in AntiMicroX enumerates **all** active input devices *(using the same library I was experimenting with for this in Volume Control, funnily enough)*, which is why they have it on a button instead of just running that in the background whenever its open.  
![image](https://user-images.githubusercontent.com/1927798/184518005-eb6a746e-7e0b-4c46-9552-29c7461b9d88.png)  
That's why many games don't recognize when you plug in a controller after starting the game; in order to do so while also picking up **all** game controllers you have to enumerate **all** input devices each time you check. Unfortunately that makes it a non-starter since even if I could do that without slowing everything else on weaker computers to a crawl, the `RegisterHotKey` function still doesn't support them directly, so I'd still have to perform the **Gamepad ➔ Keyboard** mappings anyway in order for it to work.

**Comment by Switch123456789** [comment]
>That's why many games don't recognize when you plug in a controller after starting the game; in order to do so while also picking up **all** game controllers you have to enumerate **all** input devices each time you check. Unfortunately that makes it a non-starter

The issue here is that checking for input-devices would slow down volume-control on startup? Is that correct? (just trying to understand)

> the `RegisterHotKey` function still doesn't support them directly, so I'd still have to perform the **Gamepad ➔ Keyboard** mappings anyway in order for it to work.

You are really challenging my knowledge here :D `RegisterHotKey` is a function to enable an app to register keystrokes no matter wich window is focused? Right?

**Comment by radj307** [comment]
Sorry for the delayed response, it's good to hear that you found a workaround for both issues!  

> The issue here is that checking for input-devices would slow down volume-control on startup? Is that correct? 

That's correct; however it does have the potential to affect more than just Volume Control's startup time.  Since we're getting the OS to repeatedly check and re-check all of the plugged in input devices, it has the potential to slow down the OS as well.  

> `RegisterHotKey` is a function to enable an app to register keystrokes no matter wich window is focused? Right?

That is also correct!
