### ISSUE TITLE
Consistency for Main Form Sizing

### ISSUE THREAD

**Issue by hl2guide** [radj307/volume-control#83]
Please consider standardizing the form/window dimensions for all three tabs.

This would allow for better usage when the window is positioned to the right of the display.

example:
1. launch the app
2. align the window to the bottom right of the display
3. change the tab to `Hotkeys` then `Settings`

Notice how it goes off-screen.

**Comment by radj307** [comment]
Redesigning the entire main window would be the ideal solution, but that's a lot of work and I simply don't have enough free time to do that for the foreseeable future.

An alternative solution would be to just adjust the window's position when it resizes, like the notification windows already do. Using the exact same behaviour would be weird for a main window with lots of buttons, though, as you can see in this gif:  
![positioning](https://github.com/radj307/volume-control/assets/1927798/453b8568-e74f-4919-8477-87a487994ca4)  
A naive solution would be to only adjust the position when the window goes off-screen, but that isn't ideal either since the window will become "stranded" when it gets smaller, like in this gif:  
![positioning2](https://github.com/radj307/volume-control/assets/1927798/5db236f0-4596-49f2-bbdb-d4ca018ad9de)

I could easily add a setting to enable this behaviour for those that want it. Let me know what you think.

**Comment by hl2guide** [comment]
> Redesigning the entire main window would be the ideal solution, but that's a lot of work and I simply don't have enough free time to do that for the foreseeable future.
> 
> An alternative solution would be to just adjust the window's position when it resizes, like the notification windows already do. Using the exact same behaviour by default would be weird for a main window with lots of buttons, though, as you can see in this gif: ![positioning](https://user-images.githubusercontent.com/1927798/271036277-453b8568-e74f-4919-8477-87a487994ca4.gif) [ ![positioning](https://user-images.githubusercontent.com/1927798/271036277-453b8568-e74f-4919-8477-87a487994ca4.gif) ](https://user-images.githubusercontent.com/1927798/271036277-453b8568-e74f-4919-8477-87a487994ca4.gif) [ ](https://user-images.githubusercontent.com/1927798/271036277-453b8568-e74f-4919-8477-87a487994ca4.gif) A naive solution would be to only adjust the position when the window goes off-screen, but that isn't ideal either since the window will become "stranded" when it gets smaller, like in this gif: ![positioning2](https://user-images.githubusercontent.com/1927798/271038051-5db236f0-4596-49f2-bbdb-d4ca018ad9de.gif) [ ![positioning2](https://user-images.githubusercontent.com/1927798/271038051-5db236f0-4596-49f2-bbdb-d4ca018ad9de.gif) ](https://user-images.githubusercontent.com/1927798/271038051-5db236f0-4596-49f2-bbdb-d4ca018ad9de.gif) [ ](https://user-images.githubusercontent.com/1927798/271038051-5db236f0-4596-49f2-bbdb-d4ca018ad9de.gif) _(Note: The window is in the bottom-right corner of the screen in both GIFs)_
> 
> I could easily add a setting to enable this behaviour for those that want it. Let me know what you think.

Thanks for the detailed reply for this. I think that the "adjust the window's position when it resizes" option is more feasible too and would love to see your app have this. 💓

**Comment by radj307** [comment]
Implemented in 387e3a9fb86d6544ca3d93cb56195f8f7969fe9e

**Comment by radj307** [comment]
This feature is now available in [v6.0.3](https://github.com/radj307/volume-control/releases/tag/6.0.3)

**Comment by radj307** [comment]
This feature is now available in [v6.0.3](https://github.com/radj307/volume-control/releases/tag/6.0.3)
