### ISSUE TITLE
[BUG] Run at startup doesn't work

### ISSUE THREAD

**Issue by AgenB** [radj307/volume-control#85]
### Version

6.0.3

### Windows Version

Windows 10 Pro 22H2

### Actual Behaviour

Program tries to start automatically after logging into Windows, however it crashes. I have to run it manually again for it to work.
Windows Event Viewer records 2 errors, one from .NET Runtime:

> Application: VolumeControl.exe
> CoreCLR Version: 6.0.2223.42425
> .NET Version: 6.0.22
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\VolumeControl.log' is denied.

And then right after it Application Error:

> Faulting application name: VolumeControl.exe, version: 6.0.3.0, time stamp: 0x64e810fc
> Faulting module name: KERNELBASE.dll, version: 10.0.19041.3393, time stamp: 0x6b4de7c9
> Exception code: 0xe0434352
> Fault offset: 0x000000000002cf19
> Faulting process id: 0x2514
> Faulting application start time: 0x01d9f38ea2468fe7
> Faulting application path: C:\Program Files\VolumeControl\VolumeControl.exe
> Faulting module path: C:\Windows\System32\KERNELBASE.dll
> Report Id: 97dbea2d-6e4c-4aee-8c92-0a68a071b7c2
> Faulting package full name: 
> Faulting package-relative application ID: 

### Reproduction Steps

1. Volume Control is installed in Program Files (allowed to write inside it's own folder to not use Admin privileges)
2. Tick "Run at startup" in program settings
3. Restart PC

**Comment by radj307** [comment]
Thanks for reporting this (and extra thanks for including the event logs)!

The crash is happening because for some ungodly reason the program is trying to create the log file in the `System32` directory *(which it most definitely does not - and should never - have write permissions for)*.

My hypothesis is that your log path is probably set to `VolumeControl.log` in **Settings->Event Logging**, and the program's working directory is `System32` when it is started via its registry key. This would cause the log path to resolve to `C:\Windows\System32\VolumeControl.log`.

Potential fixes for this:
- Set the working directory to an appropriate value when it is started in the `System32` directory.
- Create/delete a shortcut (which allows specifying the working directory) in `shell:startup` to run at startup instead of using the registry. (I hesitate to do this because deleting files on the user's system is almost always a terrible idea.)

**Comment by radj307** [comment]
Did you install volume control via the installer or manually by putting `VolumeControl.exe` in a program files directory yourself?

**Comment by radj307** [comment]
Fixed in 3aaf4adab8626b1c4b16d3209e8a6fd084da84bf

Now available in [v6.0.4](https://github.com/radj307/volume-control/releases/tag/6.0.4)

**Comment by AgenB** [comment]
I chose to install it for all users in the installer, but I think I had to change the permissions of the install folder to allow changes to everyone when installing some older version or else it wouldn't launch without admin privileges. I see now that both the config json and log sits in AppData by default.
