### ISSUE TITLE
Target Override for Session Volume Controls does not trigger Session Notification

### ISSUE THREAD

**Issue by Sollaze** [radj307/volume-control#87]
### Version

6.0.4

### Windows Version

Windows 10 Pro 22H2

### Actual Behaviour

When using Target Overrides to control multiple applications within a single session, the application still only respects the primary "Selected" app from the Mixer options. Thus, notifications for secondary applications will not be triggered unless they are individually selected within the Mixer.

### Expected Behaviour

Ideally there would be two ways that this issue could be remedied:

1. Allow selection of multiple applications within the Mixer which could eliminate the need for Target Overrides to an extent (or completely in my use case)
2. Allow volume changes to any of the Target Override applications to trigger the session notification.

**Comment by radj307** [comment]
Thanks for the report! I'll be able to fix this within the hour.

Your first suggestion was discussed in the original feature request, but I ended up turning it down because it would interfere too much with the behaviour of the next/previous session actions (what should happen when there are multiple sessions selected and you trigger the next session action?). You can read more about this in feature request #54.

As such, I'll be implementing your second suggestion for now as the current behaviour is a bug.

If you have any ideas about how things should behave if I were to implement the first suggestion, feel free to submit a (separate) feature request so we can discuss that further.

**Comment by radj307** [comment]
Fixed in e2fde88efbabe6ca918e472141c74e99c2f10409

**Comment by radj307** [comment]
Fix is now available in [v6.0.5](https://github.com/radj307/volume-control/releases/tag/6.0.5)

**Comment by Sollaze** [comment]
Might be worth a separate Feature Request/Bug Report but I just tried v6.0.5 and the problem I have with the current implementation is that while the notification shows up, there's no indication of what is being changed and what it's changing to.

So would it be possible to at least highlight the applications affected? Ideally, I'd love to have the sliders show up under all of the changed apps too but that can get out of hand pretty fast with multiple overrides. Maybe you could just have one slider and tie the volumes for the apps together so they are changed *to* the same volume once a hotkey is pressed?

My thinking is the app would take the volume of the opened application currently highest in the list of overrides, take its volume, and adjust all other overrides based on that volume. So as an example, I'd have apps X, Y, and Z (in that order in the override) that have their volumes set to 40, 60, and 80 respectively. Let's say X isn't open, then the app would take Y as the basis as that's the second highest priority. Then for example increasing the volume by 10 would put both Y *and* Z at 70. That way, one slider would still be enough in the notification but all overrides could be highlighted.

**Comment by radj307** [comment]
Created feature request #88 to track implementation of multi-selection feature
